Lightning-AI/ecosystem-ci

.actions/_config.yaml, .actions/assistant.py, .azure/testing-template.yml, .github/workflows/ci_testing.yml, .pre-commit-config.yaml, configs/PyTorchLightning/flash_pl-master.yaml, configs/PyTorchLightning/flash_pl-release.yaml, configs/PyTorchLightning/metrics_pl-master.yaml, configs/PyTorchLightning/metrics_pl-release.yaml, configs/PyTorchLightning/transformers_pl-master.yaml, configs/PyTorchLightning/transformers_pl-release.yaml
Fixes #13
see the result in https://pytorch-lightning.slack.com/archives/C02NJMSLFJR/p1638748576001800
=> mention slack user on failure

.azure/testing-template.yml, .github/workflows/ci_testing.yml, README.md, actions/_config.yaml, actions/assistant.py, actions/test_cli.py, configs/PyTorchLightning/metrics_pl-master.yaml, configs/PyTorchLightning/metrics_pl-release.yaml, requirements.txt
Resolves #16
**GHA** dynamically creates build matrix
**Azure** dynamically skip redundant jobs
=> built PRs differential

actions/assistant.py, configs/PyTorchLightning/flash_pl-master.yaml
align Flash also with TorchMetrics master
=> Flash: align with TorchMetrics master

.github/CODEOWNERS, configs/SeanNaren/deepspeech-release.yaml
Closes https://github.com/SeanNaren/deepspeech.pytorch/issues/671
Fixes # (issue).
=> Add DeepSpeech.pytorch

configs/PyTorchLightning/flash_pl-develop.yaml, configs/PyTorchLightning/flash_pl-release.yaml
=> Update Flash to test `image,tabular,text` extras

.github/PULL_REQUEST_TEMPLATE.md, README.md
Specify what projects and how to integrate
- CPU: anyone
- GPU: min 100+ GH stars
=> docs: add engagement rules

.azure/ci-testig-parameterized.yml, configs/microsoft/deepspeed-release.yaml
Closes https://github.com/microsoft/DeepSpeed/issues/1674.
Fixes # (issue).
=> Add DeepSpeed!

actions/_config.yaml, actions/assistant.py, configs/SeanNaren/deepspeech-release.yaml, configs/vturrisi/solo-learn_pl-develop.yaml, configs/vturrisi/solo-learn_pl-release.yaml
rename `install_file` as it was not clear what it does and allow list
=> allow multiple req. files

configs/NVIDIA/nemo-release.yaml, configs/PyTorchLightning/flash_pl-release.yaml, configs/PyTorchLightning/metrics_pl-release.yaml, configs/PyTorchLightning/transformers_pl-release.yaml, configs/SeanNaren/deepspeech-release.yaml, configs/microsoft/deepspeed-release.yaml, configs/vturrisi/solo-learn_pl-release.yaml
Setting the next release as stable... this would need to rename the PL branch, the actual `release/1.6.x` to `release/stable`
The back story is that tag and branch are almost the same and in past, we rarely release to any past feature release stream
=> update target PL/stable

.azure/testing-template.yml, actions/assistant.py, configs/PyTorchLightning/flash_pl-develop.yaml, configs/PyTorchLightning/flash_pl-release.yaml
Fixes # (issue) \[add a link to the created issue in your repository if any\]
=> Fix flash CI

configs/Lightning-AI/flash_pl-develop.yaml, configs/Lightning-AI/flash_pl-release.yaml
Fixes # (issue) \[add a link to the created issue in your repository if any\]
=> update slack person for Flash

configs/Lightning-AI/bolts_pl-develop.yaml, configs/Lightning-AI/bolts_pl-release.yaml
Fixes # (issue) \[add a link to the created issue in your repository if any\]
=> Add lightning bolts to ecosystem ci

.azure/ci-testig-parameterized.yml, .github/CODEOWNERS, actions/assistant.py, configs/neptune-ai/lightning_integration.yaml
it adds neptune.ai integration for lightning to the ecosystem
Fixes # ([807](https://github.com/neptune-ai/neptune-client/issues/807))
=> neptune.ai integration

.github/workflows/ci_test-acts.yml, .github/workflows/ci_testing.yml, actions/assistant.py, configs/Lightning-AI/bolts_pl-release.yaml, configs/Lightning-AI/flash_pl-release.yaml, configs/Lightning-AI/metrics_pl-release.yaml, configs/Lightning-AI/transformers_pl-release.yaml, configs/NVIDIA/nemo-release.yaml, configs/SeanNaren/deepspeech-release.yaml, configs/microsoft/deepspeed-release.yaml, configs/neptune-ai/lightning_integration.yaml, configs/vturrisi/solo-learn_pl-release.yaml
from Lai 1.8 we moved to `release/stable` for upcoming releases
=> switch to stable & fix CI matrix

.github/workflows/ci_compatible.yml
preserve all results in the `archive` branch which can be harmlessly reset at any time
FYI, need to have merged #85 first as it require collector :innocent: 
=> ci: archive compatibility results

.pre-commit-config.yaml, _actions/assistant.py, pyproject.toml, requirements.txt, setup.cfg
Unify project config in pyproject.toml and switch `falek8` by `ruff`
=> migrate to pyproject & ruff

configs/Lightning-AI/bolts_pl-release.yaml, configs/Lightning-AI/flash_pl-release.yaml, configs/Lightning-AI/metrics_pl-release.yaml, configs/NVIDIA/nemo-release.yaml, configs/SeanNaren/deepspeech-release.yaml, configs/manujosephv/pytorch-tabular_lit-release.yaml, configs/microsoft/deepspeed-release.yaml, configs/neptune-ai/lightning_integration.yaml, configs/vturrisi/solo-learn_lit-release.yaml
As Lightning 2.0 introduced many breaking changes, let's temporarily set the validation with LTS and update these projects one by one... :rabbit: 
closes #110
<details>
<summary>Before submitting</summary>
- Did you **set `runtimes` in config** for GitHub action integration?
</details>
=> freeze head to `release/LTS`

README.md, _actions/_config.yaml, _actions/assistant.py, configs/Lightning-AI/bolts_pl-develop.yaml, configs/Lightning-AI/bolts_pl-release.yaml, configs/Lightning-AI/flash_pl-develop.yaml, configs/Lightning-AI/flash_pl-release.yaml, configs/Lightning-AI/metrics_pl-develop.yaml, configs/Lightning-AI/metrics_pl-release.yaml, configs/NVIDIA/nemo-release.yaml, configs/SeanNaren/deepspeech-release.yaml, configs/manujosephv/pytorch-tabular_lit-release.yaml, configs/microsoft/deepspeed-release.yaml, configs/neptune-ai/lightning_integration.yaml, configs/vturrisi/solo-learn_lit-develop.yaml, configs/vturrisi/solo-learn_lit-release.yaml
this is a better name for the real source for testing as this shall include also tests and eventually dependency as the testing target could be included in `dependencies`
<details>
<summary>Before submitting</summary>
- Did you **set `runtimes` in config** for GitHub action integration?
</details>
=> rename `target_repository` & bump macOS-10.15

.azure/ci-testig-parameterized.yml, .azure/testing-template.yml, .codecov.yml, .github/actions/job-dump/action.yml, .github/actions/pytester/action.yml, .github/mergify.yml, .github/workflows/ci_compatible.yml, .github/workflows/ci_test-acts.yml, .github/workflows/dockers.yml, .pre-commit-config.yaml, .prettierignore, _actions/_config.yaml, configs/Lightning-AI/bolts_pl-develop.yaml, configs/Lightning-AI/bolts_pl-release.yaml, configs/Lightning-AI/flash_pl-develop.yaml, configs/Lightning-AI/flash_pl-release.yaml, configs/Lightning-AI/metrics_pl-develop.yaml, configs/Lightning-AI/metrics_pl-release.yaml, configs/NVIDIA/nemo-release.yaml, configs/SeanNaren/deepspeech-release.yaml, configs/manujosephv/pytorch-tabular_lit-release.yaml, configs/neptune-ai/lightning_integration.yaml, configs/vturrisi/solo-learn_lit-develop.yaml, configs/vturrisi/solo-learn_lit-release.yaml
standardize the YAML formatting
<details>
<summary>Before submitting</summary>
- Did you **set `runtimes` in config** for GitHub action integration?
</details>
=> precommit: enable prettier formatting

.pre-commit-config.yaml, _actions/assistant.py, pyproject.toml
Fixes # <issue> (add a link to the created issue in your repository if any)
<details>
<summary>Before submitting</summary>
- Did you **set `runtimes` in config** for GitHub action integration?
</details>
=> precommit: enable codespell
